version: '3'
services:
  zookeeper:
    image: debezium/zookeeper:2.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - elasticnet

  kafka:
    image: debezium/kafka:2.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - elasticnet

  connect:
    image: debezium/connect:2.3
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_PLUGIN_PATH=/usr/share/java,/kafka/connect,/kafka-connect-plugins
      - CONNECT_CONFIG_PROVIDERS=file
      - CONNECT_CONFIG_PROVIDERS_FILE_CLASS=org.apache.kafka.common.config.provider.FileConfigProvider
    volumes:
      - ./kafka-connect-plugins/confluentinc-kafka-connect-elasticsearch-14.1.2:/kafka-connect-plugins
      - ./secrets:/secrets:ro
    depends_on:
      - kafka
    networks:
      - elasticnet

networks:
  elasticnet:
    external: true
    name: elk_elasticnet
